/**
 * This file is auto-generated by scripts/generate-queue-manifest.mjs.
 * Do not edit this file manually.
 */

import type { JobRegistry } from "@shanjing/astro-full-stack-starter/queue/core";
import { BaseQueueJob } from "@shanjing/astro-full-stack-starter/queue/core";

import * as demoPageVisitJobModule from "./demo-page-visit.job.ts";
import * as dynamicQueueTestJobModule from "./dynamic-queue-test.job.ts";
import * as systemHealthCheckJobModule from "./system-health-check.job.ts";

type QueueJobConstructor = new () => BaseQueueJob<unknown>;

export interface QueueJobModule {
    registerJob?: (registry: JobRegistry) => void;
    [key: string]: unknown;
}

export const queueJobModules: QueueJobModule[] = [
    demoPageVisitJobModule,
    dynamicQueueTestJobModule,
    systemHealthCheckJobModule,
];

export function registerAllJobs(registry: JobRegistry) {
    for (const jobModule of queueJobModules) {
        let hasQueueJobClass = false;

        for (const exportedValue of Object.values(jobModule)) {
            if (typeof exportedValue !== "function") {
                continue;
            }

            if (!(exportedValue.prototype instanceof BaseQueueJob)) {
                continue;
            }

            const queueJob = new (exportedValue as QueueJobConstructor)();
            queueJob.register(registry);
            hasQueueJobClass = true;
        }

        if (!hasQueueJobClass) {
            jobModule.registerJob?.(registry);
        }
    }
}
